services:
  school-client:
    build:
      context: ./school-client
    ports:
      - "80:80"
    depends_on:
      - school-gateway
    restart: always

  school-gateway:
    build:
      context: ./school-gateway
    ports:
      - "8080:8080"
    depends_on:
      - courses-api
      - students-api
    environment:
      - COURSES_ENDPOINT=http://courses-api:8081/graphql
      - STUDENTS_ENDPOINT=http://students-api:8082/graphql
    restart: always

  courses-api:
    build:
      context: ./school-course-api
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    env_file: .env

  students-api:
    build:
      context: ./school-student-api
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    env_file: .env

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file: .env
