services:
  gateway:
    build:
      context: ./school-gateway
    ports:
      - "8080:8080"
    depends_on:
      - courses-api
      - students-api
    environment:
      - COURSES_ENDPOINT=http://courses-api:8081/graphql
      - STUDENTS_ENDPOINT=http://students-api:8082/graphql
    restart: on-failure

  courses-api:
    build:
      context: ./school-course-api
    ports:
      - "8081:8081"

  students-api:
    build:
      context: ./school-student-api
    ports:
      - "8082:8082"
